#!/usr/bin/env bash
#Add the subdomain www to your domain, point it to your lb-01 IP
#Add the subdomain lb-01 to your domain, point it to your lb-01 IP
#Add the subdomain web-01 to your domain, point it to your web-01 IP
#Add the subdomain web-02 to your domain, point it to your web-02 IP


dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
