#!/usr/bin/env bash
# Install and configure HAProxy
# Using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  dema-front
        bind *:80
        mode http
        default_backend dema-back
backend dema-back
        balance roundrobin
	server 104481-web-01    100.25.22.118:80 check
        server 104481-web-02    52.90.13.68:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to allow start with an init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
