#!/usr/bin/env bash
# Displays the contents of 'etc/passwd
# Showing 'username', 'user id' and 'Home directory path for the user'

file="etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$file"
