#!/usr/bin/env bash
# Nginx runs as nginx user on port 8080.

#  replace '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

#  permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf

# kill apache2 which may be running on 80 or 8080
pkill apache2

# service start the nginx
sudo -u nginx service nginx start
