#!/usr/bin/env bash
# run Nginx as the nginx user on port 8080.

# set a user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# give owner permissions
chmod 644 /etc/nginx/nginx.conf
# kill apache process
pkill apache2
# start the nginx service
sudo -u nginx service nginx start
